// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tamagochi.Data;

#nullable disable

namespace Tamagochi.Migrations
{
    [DbContext(typeof(TamagotchiContext))]
    [Migration("20240323162733_TabelaPokemonsUsuario")]
    partial class TabelaPokemonsUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tamagochi.Model.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonsUsuarioHabilidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonsUsuarioMascoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonsUsuarioMascoteId", "PokemonsUsuarioHabilidadeId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("Tamagochi.Model.Mascote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonsUsuarioHabilidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonsUsuarioMascoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonsUsuarioMascoteId", "PokemonsUsuarioHabilidadeId");

                    b.ToTable("Mascotes");
                });

            modelBuilder.Entity("Tamagochi.Model.PokemonsUsuario", b =>
                {
                    b.Property<int>("MascoteId")
                        .HasColumnType("int");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("int");

                    b.HasKey("MascoteId", "HabilidadeId");

                    b.ToTable("PokemonsUsuarios");
                });

            modelBuilder.Entity("Tamagochi.Model.Ability", b =>
                {
                    b.HasOne("Tamagochi.Model.PokemonsUsuario", "PokemonsUsuario")
                        .WithMany("Habilidade")
                        .HasForeignKey("PokemonsUsuarioMascoteId", "PokemonsUsuarioHabilidadeId");

                    b.Navigation("PokemonsUsuario");
                });

            modelBuilder.Entity("Tamagochi.Model.Mascote", b =>
                {
                    b.HasOne("Tamagochi.Model.PokemonsUsuario", "PokemonsUsuario")
                        .WithMany("Mascote")
                        .HasForeignKey("PokemonsUsuarioMascoteId", "PokemonsUsuarioHabilidadeId");

                    b.Navigation("PokemonsUsuario");
                });

            modelBuilder.Entity("Tamagochi.Model.PokemonsUsuario", b =>
                {
                    b.Navigation("Habilidade");

                    b.Navigation("Mascote");
                });
#pragma warning restore 612, 618
        }
    }
}
